[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://api.openweathermap.org; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' https://openweathermap.org"
